---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 'https://api.stackbit.com/project/60d5d4937cca550016e54322/webhook/forestry'
sections:
- type: document
  path: _data/config.json
  label: Site Configuration
  templates:
  - config
- type: document
  path: blog/index.md
  label: Blog
  templates:
  - blog
- type: jekyll-pages
  label: Pages
  create: all
  exclude: '{README.md,LICENSE.md}'
  new_doc_ext: md
  templates:
  - advanced
  - page
- type: jekyll-posts
  label: Posts
  create: all
  new_doc_ext: md
  templates:
  - post
upload_dir: images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
